# Stage 1: Build stage
FROM eclipse-temurin:17 AS builder
WORKDIR /build

# Copy the inner BACKEND folder (actual project)
COPY BACKEND ./BACKEND

# Go inside actual project folder
WORKDIR /build/BACKEND

# Give permission to wrapper
RUN chmod +x mvnw

# Build Spring Boot JAR
RUN ./mvnw clean package -DskipTests

# Stage 2: Run stage
FROM eclipse-temurin:17
WORKDIR /app

# Copy built jar
COPY --from=builder /build/BACKEND/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
